/*
 * This file is generated by jOOQ.
 */
package org.dakhli.elyes.contactapp.infra.data.jooq.model.tables.records;


import org.dakhli.elyes.contactapp.infra.data.jooq.model.tables.Contact;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContactRecord extends UpdatableRecordImpl<ContactRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.CONTACT.ID</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.CONTACT.ID</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>PUBLIC.CONTACT.FIRSTNAME</code>.
     */
    public void setFirstname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.CONTACT.FIRSTNAME</code>.
     */
    public String getFirstname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.CONTACT.LASTNAME</code>.
     */
    public void setLastname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.CONTACT.LASTNAME</code>.
     */
    public String getLastname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.CONTACT.TEL</code>.
     */
    public void setTel(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.CONTACT.TEL</code>.
     */
    public String getTel() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.CONTACT.EMAIL</code>.
     */
    public void setEmail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.CONTACT.EMAIL</code>.
     */
    public String getEmail() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContactRecord
     */
    public ContactRecord() {
        super(Contact.CONTACT);
    }

    /**
     * Create a detached, initialised ContactRecord
     */
    public ContactRecord(String id, String firstname, String lastname, String tel, String email) {
        super(Contact.CONTACT);

        setId(id);
        setFirstname(firstname);
        setLastname(lastname);
        setTel(tel);
        setEmail(email);
        resetChangedOnNotNull();
    }
}
