spring:
  application:
    name: contact-app
  datasource:
    url: jdbc:h2:file:D:/dev/workspace/contact-app/contact-app-db
    username: admin
    password: admin
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
