spring:
  application:
    name: contact-app
  datasource:
    url: jdbc:postgresql://localhost:5432/contact-app
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: public
  jooq:
    sql-dialect: postgres
  jpa:
    show-sql: true
