/*
 * This file is generated by jOOQ.
 */
package org.dakhli.elyes.contactapp.infra.data.jooq.model;


import org.dakhli.elyes.contactapp.infra.data.jooq.model.tables.Contact;
import org.dakhli.elyes.contactapp.infra.data.jooq.model.tables.records.ContactRecord;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ContactRecord> CONSTRAINT_6 = Internal.createUniqueKey(Contact.CONTACT, DSL.name("CONSTRAINT_6"), new TableField[] { Contact.CONTACT.ID }, true);
}
