/*
 * This file is generated by jOOQ.
 */
package org.dakhli.elyes.contactapp.infra.data.jooq.model;


import org.dakhli.elyes.contactapp.infra.data.jooq.model.tables.Contact;


/**
 * Convenience access to all tables in PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.CONTACT</code>.
     */
    public static final Contact CONTACT = Contact.CONTACT;
}
